name: Reusable java
on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use'
        required: true
        type: string
      artifact-name:
        description: 'Name of the artifact to upload'
        required: false
        type: string
        default: 'Package'
      distribution:
        description: 'type distribution Java'
        required: true
        type: string
        default: 'temurin'
     
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2  

      - name: Build and test project with Maven
        run: mvn -B package --file pom.xml

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          cache: 'maven'

      - name: Create Package JAR
        run: mvn -B package --file pom.xml -DskipTests

      - name: Copy Package Directory sta 
        run: mkdir packagejar && cp target/*jar-with-dependencies.jar packagejar
        continue-on-error: false
      
  upload-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: packagejar
          retention-days: 7
